services:
  # Combined service for both frontend and backend
  - type: web
    name: e-commerce-website
    env: node
    buildCommand: npm install && npm run build:frontend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
