services:
  # Combined service for both frontend and backend
  - type: web
    name: e-commerce-website
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: VITE_BACKEND_URL
        value: https://e-commerce-website-curh.onrender.com/api
